[project]
name = "adiabatic-flame-temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chempy>=0.10.1",
    "dash>=3.2.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "plotly>=6.4.0",
    "scipy>=1.16.3",
]
